### ISSUE TITLE
Change power button behaviour

### ISSUE THREAD

**Issue by Pintjebier** [EliverLara/AndromedaLauncher#15]
Hi, I love this plasmoid especially in a dock, but after the recent Plasma update to 6.1 the power button now only displays the shutdown option and leave the other options like restart or log off behind as mentioned in the change logs from KDE.
Could you change this behavior or add buttons to restart and log off as well, please?

Thanks a million!

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very very late response(github never notified me anything about this repo) but in case you're still using this launcher I'm planning on adding  such feature ASAP.

**Comment by Cherkah** [comment]
same issue hier.

**Comment by EliverLara** [comment]
Added in 96423d720788789be675ce01acd2b8ec38a73296 :)
