### ISSUE TITLE
Screen lock button

### ISSUE THREAD

**Issue by matiux** [EliverLara/AndromedaLauncher#4]
I was wondering if there a way to add the lock screen button of, if not possible, replace settings button

![Screenshot_20240501_014018](https://github.com/EliverLara/AndromedaLauncher/assets/821668/c91f11a3-e9e0-4be7-acec-2bf6680d7a8e)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very very late response(github never notified me anything about this repo) but, in case you're still using it, your request is for plasma 6 right?

**Comment by matiux** [comment]
No problem @EliverLara. Yes, I was referred to Plasma 6.

**Comment by EliverLara** [comment]
Added in 96423d720788789be675ce01acd2b8ec38a73296 :)

**Comment by matiux** [comment]
Thanks @EliverLara 
How can update the launcher?
I installed the launcher by kde widget

**Comment by matiux** [comment]
Nothing seems to be changed

![WhatsApp Image 2024-10-03 at 09 19 24 (1)](https://github.com/user-attachments/assets/15fbf8c7-e7ce-4c45-abda-d6a052057531)

**Comment by matiux** [comment]
@EliverLara after restarting the PC, it works now :) Thanks!

P.s. what icons are you using? :)

**Comment by EliverLara** [comment]
Those are [candy-icons](https://www.gnome-look.org/p/1305251/) :)
