### ISSUE TITLE
Recent Applications?

### ISSUE THREAD

**Issue by benjamindaines** [EliverLara/AndromedaLauncher#9]
Going through and setting "Favorite" applications is pointless for my workflow (and other's I'm sure).  The ability to display recent applications when opening the launcher would be much better!  Perhaps an option to switch between the two?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very very late response(github never notified me anything about this repo)  but I think it would be a nice and helpful addition, Are you using plasma 6?

**Comment by benjamindaines** [comment]
Yes, Plasma 6. Thanks for following up

**Comment by EliverLara** [comment]
Added in 199b2eee1960fc84740d0819754dbc7cf7953c8d :)
